name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: docker login
      env:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build and push to docker 
      run: docker build. -- file Dockerfil e-- tag FlightProgram/backend:$(date + %s)
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/flightprogrambackend
